fix(build): Fix Cpp build errors in recent github actions (#1834)
Mute errors like the follows, the Pegasus codebase will be checked by clang-format, so it's safe to enable the CMake option (-Wno-misleading-indentation).
```
  # .../thirdparty/output/include/boost/lexical_cast/detail/lcast_unsigned_converters.hpp:149:17: error: this 'while' clause does not guard... [-Werror=misleading-indentation]
  # 149 |             inline CharT* main_convert_loop() BOOST_NOEXCEPT {
  #     |                 ^~~~~
```