fix(build): fix undefined reference to thrift-generated objects while linking libdsn_client.a (#1847)
#1846

The module replication_ddl_client in libdsn_client.a has referenced
thrift-generated objects, which are included in libdsn_replication_common.a
Thus, libdsn_replication_common.a should be linked privately to
libdsn_client.a.